set background=dark
set termguicolors
colorscheme material-monokai

let g:materialmonokai_italic=1
let g:airline_theme='materialmonokai'

set guifont=Monaco\ Regular:h16
set colorcolumn=80
set number
